[variables]
NIXPACKS_PYTHON_VERSION = "3.11"

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[start]
cmd = "python main.py --host 0.0.0.0 --port $PORT --load-only en,fr,es --threads 2"
